repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.6.0
    hooks:
    -   id: trailing-whitespace
        exclude: '(^Third_Party|.*\.md|.*\.rst)'
    -   id: end-of-file-fixer
        exclude: '(^Third_Party|.*\.md|.*\.rst)'
    -   id: check-added-large-files
    -   id: debug-statements  # check for debugger imports or `breakpoint()`
    -   id: check-yaml
    -   id: check-toml

-   repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.11.7
    hooks:
    -   id: ruff
        args: [ --fix ]
        exclude: '(^Third_Party|.*\.md|.*\.rst)'
    -   id: ruff-format
        exclude: '(^Third_Party|.*\.md|.*\.rst)'
